### ISSUE TITLE
error to run the project on iPhone simulator

### ISSUE THREAD

**Issue by CavalcanteLeo** [ganeshrvel/flutter_mobx_dio_boilerplate#1]
as the image bellow:

<img width="721" alt="Captura de Tela 2020-07-16 às 18 36 11" src="https://user-images.githubusercontent.com/1735944/87725250-521d6700-c793-11ea-8951-387d9e3d8976.png">

**Comment by ganeshrvel** [comment]
It should be a version specific issue. It should have been fixed by now.

**Comment by ganeshrvel** [comment]
Feel free to modify the router type in [lib/common/router/router.dart](https://github.com/ganeshrvel/flutter_mobx_dio_boilerplate/blob/master/lib/common/router/router.dart) as required and run the builder script.
Reload the app
