### ISSUE TITLE
Returning List API Response

### ISSUE THREAD

**Issue by MarlonJD** [ganeshrvel/flutter_mobx_dio_boilerplate#2]
I have tried so much different code but still couldn't get work with API responses with List. For Example https://jsonplaceholder.typicode.com/posts i tried this api and cannot work :( DC. Is there anyone to help to do this example? I tried so much hour and stucked. Please help :)

**Comment by ganeshrvel** [comment]
What is the error that you are getting?

Please log your code and out put here

**Comment by MarlonJD** [comment]
I created a system with retrofit, equatable, your dio system. I was getting NoMethodError when json response is list. İf the one object getting not getting error but in the list I'm getting. I disabled ApiErrorMessageInterceptor on apiClient for solution. Now i successfully getting list from jsonplacerholder. İ can share pull request for project for this

**Comment by ganeshrvel** [comment]
Could you push the code to your repo and comment a link here?
