### ISSUE TITLE
Upgrade to Flutter 2 & Null Safety

### ISSUE THREAD

**Issue by MarlonJD** [ganeshrvel/flutter_mobx_dio_boilerplate#3]
Any plans to upgrade to flutter 2 ?

**Comment by ganeshrvel** [comment]
i was working on this today, but the build runner isnt holding up

**Comment by MarlonJD** [comment]
build_runner showing not support but it's supporting. Disable when upgrading packages then activate again. I created issue about this on flutter build but they say it's working on flutter 2 and null safety.

Another issue about the data_connection_checker: ^0.3.4, it's not support null safety. Can we use another package for data connection ?

**Comment by MarlonJD** [comment]
Any progress? Is there any part that i can help?

**Comment by ganeshrvel** [comment]
I am unable to find time to migrate the boilerplate to null safety. Please feel free to raise a PR!


Thanks

**Comment by ganeshrvel** [comment]
https://github.com/ganeshrvel/flutter_mobx_dio_boilerplate/pull/5/ added the support for Flutter 2.0 null safety.
