### ISSUE TITLE
Upgrade Dio ApiClient with latest dio package version 

### ISSUE THREAD

**Issue by iqboladahamjonov** [ganeshrvel/flutter_mobx_dio_boilerplate#4]
I really liked the boilerplate. However, the project needs some update. I especially need upgraded dio boilerplate as I am currently working on project which uses latest dio version. Thank you.

**Comment by ganeshrvel** [comment]
https://github.com/ganeshrvel/flutter_mobx_dio_boilerplate/pull/5 now supports the latest version of dio.

Thanks for the comments!
